### ISSUE TITLE
There is some issues in the calculation part when user initiates cancel order.

### ISSUE THREAD

**Issue by smartupnish** [mohamedsamara/mern-ecommerce#80]
**Steps to reproduce**
1. User adds product/item into the cart.
![image](https://user-images.githubusercontent.com/64981592/126909638-7098453a-0e75-46a4-bb3c-8ba6249fe151.png)
2. User places the order and click on order ID to view the order details.
![image](https://user-images.githubusercontent.com/64981592/126909661-91b65d63-f46e-474c-877e-3329ac1669a6.png)
3. Verify the calculations before initiating cancel any order from the Order List. (56.8$ in my case)
![image](https://user-images.githubusercontent.com/64981592/126909673-a38e5f9c-5081-4c23-b025-8aae768f758f.png)
4. Calculations after cancellation show incorrect behavior.
**Before cancellation**
![image](https://user-images.githubusercontent.com/64981592/126909725-725ecfa9-4618-48fc-bcbc-2cee76780064.png)
**After cancellation**
![image](https://user-images.githubusercontent.com/64981592/126909745-fd355c35-5fb8-4fe6-b777-14ccbb4c71eb.png)
**After refreshing the page**
![image](https://user-images.githubusercontent.com/64981592/126909790-c414e058-2220-4e4b-b261-8e8f6ed6dfd9.png)

**Expected**: The calculation should change just after the confirmation with the cancellation part of an order. 
**Actual**: Calculation changes when the user refreshes the page.

**Comment by smartupnish** [comment]
@mohamedsamara @karthikeyana Please note that the Estimated tax also dropped after the completion of cancellation.

**Comment by mohamedsamara** [comment]
@smartupnish yes the total tax will be recalculated when items are cancelled. I pushed a fix for the refresh issue.

**Comment by smartupnish** [comment]
Thanks, I'll check it out and let you know once it's done.

**Comment by smartupnish** [comment]
Still not working, 
![image](https://user-images.githubusercontent.com/64981592/127247163-25db4eba-abb2-4169-8312-48b556c337cf.png)
Shows the same price in the total after canceling the order.
